//@version=5
indicator(title='Order Short', shorttitle='Short', overlay=true)

ATR       = request.security(syminfo.tickerid,'D',ta.atr(5),lookahead=barmerge.lookahead_on)
ATRpct    = (ATR/close)*100
ATR_1_pct = ATRpct*0.01
leverage  = math.ceil(30/(ATR_1_pct*10))

SHORT_TF_PT   = close-(ATR*0.1)
SHORT_TF_LC   = close+(ATR*0.2)
SHORT_MA_LC   = close+(ATR*0.03)

plot(leverage,    "Leverage  #0", display=display.none)
plot(SHORT_TF_PT, 'SHORT TrendFollow/SHORTMovingAverage ProfitTake #1', display=display.none)
plot(SHORT_TF_LC, 'SHORT TrendFollow StopLoss     #2', display=display.none)
plot(SHORT_MA_LC, 'SHORT MovingAverage StopLoss   #3', display=display.none)


TF_orderCond = close > 0
alertcondition(TF_orderCond,"SHORT_TrendFollow", message ='{ "x_PT":{{plot_1}},"x_SL":{{plot_2}}, "x_side":"BUY", "x_leverage":{{plot_0}},"x_symbol":"{{ticker}}"}')

MA_orderCond = close > 0
alertcondition(MA_orderCond,"SHORT_MovingAverage", message ='{ "x_PT":{{plot_1}},"x_SL":{{plot_3}}, "x_side":"BUY", "x_leverage":{{plot_0}},"x_symbol":"{{ticker}}"}')

SHORT_PT_LINE  = line.new(bar_index[1000],timeframe.period=="1"?SHORT_TF_PT:na, bar_index+ 15 ,SHORT_TF_PT, color = color.new(color.aqua,0), style=line.style_dotted)
line.delete(SHORT_PT_LINE[1])
SHORT_LC_LINE  = line.new(bar_index[1000], timeframe.period=="1"?SHORT_TF_LC:na, bar_index+ 15, SHORT_TF_LC, color = color.new(#ff0000,0), style=line.style_dotted)
line.delete(SHORT_LC_LINE[1])

var table TableA = table.new(position.top_right, 10, 10)
table.cell(TableA,0,0, str.tostring(syminfo.ticker)+"\n"+str.tostring(math.round(ATRpct,1))+"%"+" Lv."+str.tostring(leverage), text_color = color.new(#ffffff,0),text_halign=text.align_left)
